name: 'dotnet publish'
description: 'publish dotnet application' 
runs:
  using: composite
  steps:

    - name: Publish dotnet application (if need it)
      shell: bash
      run: |
        if [!-d "./compile"]; then 
          make compile            
        fi
