apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-auth-ingress
  namespace: backend
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-ecommerce-auth
spec:
  tls:
    - hosts:
      - auth.zzzemoji.com
      secretName: letsencrypt-ecommerce-auth
  rules:
  - host: auth.zzzemoji.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ecommerce-auth-service
            port:
              number: 80