apiVersion: cert-manager.io/v1
kind: Issuer
metadata: 
  name: letsencrypt-ecommerce-auth
  namespace: backend
spec:
  acme:
    email: brian71742@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-ecommerce-auth-private-key
    solvers:
      # Use the HTTP-01 challenge provider
      - http01:
          ingress:
            class: nginx