name: Integration

# Trigger
on: 
  pull_request:
    branches:
    - develop

jobs: 

  # Jobs - Unit Test
  test:
    runs-on: ubuntu-latest
    steps:
    # description - 
    #     what is checkout action do, it checks-out your repository under $GITHUB_WORKSPACE, 
    #     so your workflow can access it.
    - name: Get Code
      uses: actions/checkout@v3
    # description - 
    #     download dotnet 
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: '6.0.x'
    # description -
    #     Restore Dependencies 
    - name: Restore Dependnecies
      run: dotnet restore
    # description
    #     Build Solution
    - name: Build
      run: dotnet build --no-restore
    # description -
    #     Doing the unit test
    - name: Test
      run: dotnet test --no-build

  # Jobs - Build Image
  build:
    runs-on: ubuntu-latest
    steps:
    # description - get code
    - name: Get Code
      uses: actions/checkout@v3
    # description - login to DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    # description - compile the code
    - name: Compile The Code
      run: make compile
    # description - show the image & tag
    - name: Show Version
      run: make print_version
    # description - build docker image 
    - name: Build Docker Image
      run: make publish