name: Publish

on:
  pull_request:
    branches:
    - develop
    types:
    - closed
  workflow_dispatch:

jobs:

  # Job - build image and push it into DockerHub 
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

      # description - get code
      - name: Get Code
        uses: actions/checkout@v3

      # description - 
      #     Get current time
      #     https://github.com/marketplace/actions/get-current-time
      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with: 
          format: YYYYMMDD-HH
          utc: "+08:00"
      
      # description - Get version number
      - name: Get version number
        run: echo "VERSION=$(make version)" >> $GITHUB_ENV

      # description - login to DockerHub      
      - name: Login To DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # description - Docker meta
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: supojen/education-auth
          tags: |
            type=sha,prefix=${{ steps.current-time.outputs.formattedTime }},format=short

      # description - Check if compile directory exists
      - name: Check if compile directory exists
        id: check_directory
        uses: andstor/file-existence-action@v2
        with: 
          files: compile

      # description - download dotnet (if compile directory is not exists)
      - name: Setup Dotnet (if compile directory is not exists)
        if: steps.check_directory.outputs.files_exists == 'false'
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: '6.0.x'

      # description - Publish dotnet application (if compile directory is not exists)
      - name: Publish dotnet application (if compile directory is not exists)
        if: steps.check_directory.outputs.files_exists == 'false'
        run: . ./publish.sh

      # description - Build and push docker image
      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: . 
          push: true
          tags: ${{ steps.meta.outputs.tags }}



