name: Publish

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
    - develop
    types:
    - closed
  workflow_dispatch:

jobs:

  # Job - build image and push it into DockerHub 
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env: 
      version: '100.0.0'
    steps:

      # description - get code
      - name: Get Code
        uses: actions/checkout@v3
      
      # description - login to DockerHub      
      - name: Login To DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # description - Docker meta
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: supojen/education-auth
          tags: |
            type=semver,pattern={{raw}}
            type=sha,prefix=,format=short

      # description - 取得版本號
      #- name: Get Version Number
      #  run: |   
      #    make version
      #    echo "version=${VERSION}" >> $GITHUB_ENV
      
      # description - 測試版本號是否有成功被設定
      - name:  Test env variable
        run: env

      # description - build the application
      - name: Build application
        run: make compile

      # description - Build and push docker image
      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: . 
          push: true
          tags: ${{ steps.meta.outputs.tags }}


