name: Publish

on:
  pull_request:
    branches:
    - develop
    types:
    - closed
  workflow_dispatch:

jobs:

  # Job - build image and push it into DockerHub 
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

      # description - get code
      - name: Get Code
        uses: actions/checkout@v3
      
      # description - login to DockerHub      
      - name: Login To DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # description - Extract image's tag from DockerHub
      - name: Extract metadata (tags, labels) for docker
        uses: docker/metadata-action@v4
        with:
          images: docker.io/${{github.repository}}
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      # description - build the application
      - name: Build application
        run: make compile

      # description - Build and push docker image
      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: . 
          push: true
          tags: ${{ steps.meta.outputs.tags }}


