name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
      
jobs:


  check:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.check_step.outputs.branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Default: 1
          fetch-depth: 0

      - name: Get current branch
        id: check_step
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw/origin\/}
          echo 'branch=${{ github.event.base_ref }}' >> $GITHUB_OUTPUT
          echo 'Branch is $branch'

  release:
    runs-on: ubuntu-latest
    needs: check 
    if: ${{ needs.check.outputs.branch == 'refs/heads/develop' }}
    steps:

      - name: Echo branch
        run: echo '${{ github.event.base_ref }}'

      # description - get code
      - name: Get Code
        uses: actions/checkout@v3
      
      # description - login to DockerHub      
      - name: Login To DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # description - Docker meta
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: supojen/education-auth
          tags: |
            type=semver,pattern={{raw}}
      
      # description - Check if compile directory exists
      - name: Check if compile directory exists
        id: check_directory
        uses: andstor/file-existence-action@v2
        with: 
          files: compile

      # description - Build and push docker image
      - name: Build and push docker image
        if: steps.check_directory.outputs.files_exists == 'true'
        uses: docker/build-push-action@v3
        with:
          context: . 
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      # description - 
      #     Merge from develop to main
      #     https://github.com/marketplace/actions/merge-branch
      - name: Merge from develop to main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: develop
          target_branch: main
          github_token: ${{ github.token }} 
          