name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
      
jobs:

  release:
    runs-on: ubuntu-latest
    steps:

      # description - Get branch names
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v6

      # description - get code
      - name: Get Code
        uses: actions/checkout@v3

      # description - doing unit test
      - name: unit test
        uses: ./.github/actions/unit_test
      
      # description - login to DockerHub      
      - name: Login To DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # description - Docker meta
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: supojen/education-auth
          tags: |
            type=semver,pattern={{raw}}
      
      # description - Check if compile directory exists
      - name: Check if compile directory exists
        id: check_directory
        uses: andstor/file-existence-action@v2
        with: 
          files: compile

      # description - Build and push docker image
      - name: Build and push docker image
        if: steps.check_directory.outputs.files_exists == 'true'
        uses: docker/build-push-action@v3
        with:
          context: . 
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      # description - 
      #     pull request (XXX --> develop)
      #     https://github.com/marketplace/actions/github-action-for-creating-pull-requests
      - name: Pull Request XXX --> develop
        if: ${{ steps.branch-name.outputs.current_branch }} != 'develop'
        uses: devops-infra/action-pull-request@v0.5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: develop
          title: 'release - ${{ github.ref_name }}'
          body: ${{ github.event.head_commit.message }}

      # description - 
      #     pull request (develop --> main)
      #     https://github.com/marketplace/actions/github-action-for-creating-pull-requests
      - name: Pull Request XXX --> develop
        uses: devops-infra/action-pull-request@v0.5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: develop
          target_branch: main
          title: 'release - ${{ github.ref_name }}'
          body: ${{ github.event.head_commit.message }}    


      ## description - 
      ##     Create Pull Request (xxx branch to develop branch)
      ##     https://github.com/marketplace/actions/create-pull-request
      #- name: Create Pull Request (xxx branch to develop branch)
      #  uses: peter-evans/create-pull-request@v4
      #  with:
      #    branch: "develop"
      #    delete-branch: false
      #    title: 'release - ${{ github.ref_name }}'
      #    body:
      #      ${{ github.event.head_commit.message }}
      #    team-reviewers: |
      #      owners
      #      maintainers
      #    milestone: 1

      ## description - 
      ##     Create Pull Request (develop branch to main branch)
      ##     https://github.com/marketplace/actions/create-pull-request
      #- name: Create Pull Request (develop branch to main branch)
      #  uses: peter-evans/create-pull-request@v4
      #  with:
      #    branch: "main"
      #    base: "develop"
      #    delete-branch: false
      #    title: 'release - ${{ github.ref_name }}'
      #    body:
      #      ${{ github.event.head_commit.message }}
      #    team-reviewers: |
      #      owners
      #      maintainers
      #    milestone: 1