name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
      
jobs:

  release:
    runs-on: ubuntu-latest
    steps:

      # description - 
      #     Get branch names
      #     https://github.com/marketplace/actions/branch-names
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v6

      # description - Weather the current branch is develop
      - name: If branch is not develop, exists
        if: ${{ steps.branch-name.outputs.current_branch }}" != 'develop'
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Release process can only be luanched by develop branch')

      # description - get code
      - name: Get Code
        uses: actions/checkout@v3
      
      # description - login to DockerHub      
      - name: Login To DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # description - Docker meta
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: supojen/education-auth
          tags: |
            type=semver,pattern={{raw}}
      
      # description - Check if compile directory exists
      - name: Check if compile directory exists
        id: check_directory
        uses: andstor/file-existence-action@v2
        with: 
          files: compile

      # description - Build and push docker image
      - name: Build and push docker image
        if: steps.check_directory.outputs.files_exists == 'true'
        uses: docker/build-push-action@v3
        with:
          context: . 
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      # description - 
      #     Merge from develop to main
      #     https://github.com/marketplace/actions/merge-branch
      - name: Merge from develop to main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: develop
          target_branch: main
          github_token: ${{ github.token }} 
          